# Generated by Django 3.2.6 on 2021-08-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210823_2055'),
        ('myapp', '0002_auto_20210823_2217'),
    ]

    operations = [
    ]
