# Generated by Django 2.2.5 on 2021-08-28 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_juego', '0003_auto_20210828_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='respuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_juego.ElegirRespuesta'),
        ),
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='triviaUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='app_juego.TriviaUsuario'),
        ),
    ]
