# Generated by Django 2.2.5 on 2021-08-28 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_juego', '0002_preguntasrespondidas_triviausuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elegirrespuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='app_juego.Pregunta'),
        ),
    ]
