# Generated by Django 3.2.6 on 2021-08-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_juego', '0004_auto_20210828_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elegirrespuesta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='triviausuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
